packaging_format = 2

id = "kitchenowl"
name = "KitchenOwl"
description.en = "Self-hosted grocery list and recipe manager"
description.fr = "Gestionnaire de listes de courses et de recettes auto-hébergé"

version = "0.4.7~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://kitchenowl.org/"
demo = "https://app.kitchenowl.org/"
admindoc = "https://docs.kitchenowl.org/"
userdoc = "https://docs.kitchenowl.org/getting-started/tips-and-tricks/"
code = "https://github.com/TomBursch/kitchenowl"
fund = "https://github.com/sponsors/TomBursch"

[integration]
yunohost = ">= 11.2.3"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kitchenowl"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.front]

        url ="https://github.com/TomBursch/kitchenowl/releases/download/v0.4.8/kitchenowl_Web.tar.gz"
        sha256 ="d2a6e6d11c84db30671335d3ea2acdf7928ded59934e3c62c1cc666f9417c1fa"
        autoupdate.strategy = "latest_github_tag"


        [resources.sources.backend]
        url = "https://github.com/TomBursch/kitchenowl-backend/archive/refs/heads/main.zip"
        sha256 = "0be5f1334b43c6f2e8231420e23b56b2a2b4e9a17b74eaa16495c1c6757e406c"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
   
    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3-venv"

    [resources.database]
    type = "postgresql"
