packaging_format = 2

id = "kitchenowl"
name = "KitchenOwl"
description.en = "Self-hosted grocery list and recipe manager"
description.fr = "Gestionnaire de listes de courses et de recettes auto-hébergé"

version = "0.5.2~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://kitchenowl.org/"
demo = "https://app.kitchenowl.org/"
admindoc = "https://docs.kitchenowl.org/"
userdoc = "https://docs.kitchenowl.org/getting-started/tips-and-tricks/"
code = "https://github.com/TomBursch/kitchenowl"
fund = "https://github.com/sponsors/TomBursch"

[integration]
yunohost = ">= 12.0"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kitchenowl"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.main]
        url ="https://github.com/TomBursch/kitchenowl/archive/refs/tags/v0.5.2.tar.gz"
        sha256 ="afa660b7cf59d35d65202ba99bf6283d8ef29cbdd809f1fc9851882e92a2e2b6"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
   
    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080
    backend.default = 5000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3-dev, python3-venv"

    [resources.database]
    type = "postgresql"
