packaging_format = 2

id = "kitchenowl"
name = "KitchenOwl"
description.en = "Self-hosted grocery list and recipe manager"
description.fr = "Gestionnaire de listes de courses et de recettes auto-hébergé"

version = "0.5.2~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://kitchenowl.org/"
demo = "https://app.kitchenowl.org/"
admindoc = "https://docs.kitchenowl.org/"
userdoc = "https://docs.kitchenowl.org/getting-started/tips-and-tricks/"
code = "https://github.com/TomBursch/kitchenowl"
fund = "https://github.com/sponsors/TomBursch"

[integration]
yunohost = ">= 12.0"
architectures = ["amd64", "arm64"]
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/kitchenowl"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]
        [resources.sources.front]
        url ="https://github.com/TomBursch/kitchenowl/releases/download/v0.5.2/kitchenowl_Web.tar.gz"
        sha256 ="e2d85ea8f60b3b59cba95722d9477fc9ac32b2cb4b5457cbed772f99e43d078b"
        autoupdate.strategy = "latest_github_release"

        [resources.sources.backend]
        url = "https://github.com/TomBursch/kitchenowl/releases/download/v0.5.2/kitchenowl_Linux.tar.gz"
        sha256 = "f5399ee55a751b6a955a3c95f9282ad09f981539e57d26bf95340cace2a3b366"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
   
    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080
    backend.default = 5000

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3-dev, python3-venv"

    [resources.database]
    type = "postgresql"
